*"* use this source file for your ABAP unit test classes

CLASS ltcl_base DEFINITION DEFERRED.
CLASS zcl_prometheus_rest_resource DEFINITION LOCAL FRIENDS ltcl_base.

CLASS ltcl_base DEFINITION FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS.

  PUBLIC SECTION.
  PROTECTED SECTION.
    DATA: cut  TYPE REF TO zcl_prometheus_rest_resource.
  PRIVATE SECTION.
    METHODS:
      setup.
ENDCLASS.

CLASS ltcl_base IMPLEMENTATION.

  METHOD setup.
    CREATE OBJECT me->cut.
  ENDMETHOD.

ENDCLASS.

CLASS ltcl_get DEFINITION FINAL INHERITING FROM ltcl_base FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS.

  PRIVATE SECTION.
    METHODS:
      happy_path FOR TESTING RAISING cx_static_check.
ENDCLASS.


CLASS ltcl_get IMPLEMENTATION.

  METHOD happy_path.
  ENDMETHOD.

ENDCLASS.
